# These are supported funding model platforms. GitHub will use these to add funding links to the Sponsors page.
github: # Replace with a GitHub Sponsors username when available
custom: # Add up to 4 community/private funding sources here if desired